[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "pdoc-test"
requires-python = ">=3.8"
dependencies = [
    'numpy', 'pdoc'
]

[tool.setuptools.packages.find]
where = ["."]
